### ISSUE TITLE
API limit? 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by renoust** [tell-k/goolabs#2]
Hi!

Thanks a lot for the very good and useful API!! Dreamt of it for a while.
Something is strange, things are working very fine, but after around 2000 queries, I get the
following error: 400 Client Error: Bad Request
The things seems restarting the following day.
This seems to be an API limitation so I scouted the Goolabs website to look for any explicit recommendation and limitation, and I couldn't find any.

Do you have any idea on the limitation? or conditions not to be "blocked" for 24h? I have quite an interesting archive of Japanese news I would like to process (it's ok if I do it slowly, but 2000 queries a day is really too low, one file may be around 20 queries). 

Thanks a lot for your help!

**Comment by tell-k** [comment]
@renoust 

Sorry for my late reply.

I do not know much about API limitation too.
You can try to inquiry from the following URL.

https://goo.e-srvc.com/app/ask/p/929/rnt_subject/%E3%83%A9%E3%83%9C%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%81%8A%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B

I'm sorry that I was not able to be helpful.

Thx
